apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: your-email@example.com  # Replace with your email
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        azureDNS:
          subscriptionID: your-subscription-id
          resourceGroupName: your-resource-group
          hostedZoneName: your-dns-zone
          environment: AzurePublicCloud
          managedIdentity:
            clientID: your-client-id
