apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-actions-cluster-admin
subjects:
- kind: User
  name: $SERVICE_PRINCIPAL_OBJECT_ID  # Replace this with the Object ID from step 1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
