apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi   
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      {{- if .Values.isOpenShift }}
      serviceAccountName: {{ .Release.Namespace }}-getapp-run-as-root
      serviceAccount: {{ .Release.Namespace }}-getapp-run-as-root
      {{- end }}
      containers:
      - name: postgres  
        {{- if .Values.isOpenShift }}
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        {{- end }}
        resources: {}
        image: "{{ .Values.repository }}postgres:14.1"
        env:
        - name: POSTGRES_DB
          value: getapp           # Name of the database
        - name: POSTGRES_USER
          value: getapp        # Database user
        - name: POSTGRES_PASSWORD
          value: "Fw|G0f>r(;;p{cyQ:{_8-N.5"
        - name: PGDATA
          value: /var/lib/postgresql/data/getapp  # Use the subdirectory "nextcloud" as the data directory
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data/   # Mount the subdirectory
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres
