kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker
  labels:
    getapp: kafka
    chart: {{ template "getapp-api.chart" . }}
    draft: {{ .Values.draft | default "draft-app" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    gitlabrelease: "{{ .Values.gitlabrelease }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      {{- if .Values.isOpenShift }}
      serviceAccountName: {{ .Release.Namespace }}-getapp-run-as-root
      serviceAccount: {{ .Release.Namespace }}-getapp-run-as-root
      {{- end }}
      containers:
        - resources: {}
          name: broker
          env:
            - name: KAFKA_BROKER_ID
              value: '1'
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: >-
                PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
            - name: KAFKA_ADVERTISED_LISTENERS
              value: >-
                PLAINTEXT://kafka-broker-service:29092,PLAINTEXT_HOST://kafka-broker-service:9092
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: '1'
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: '0'
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: '1'
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: '1'
            - name: KAFKA_PROCESS_ROLES
              value: 'broker,controller'
            - name: KAFKA_NODE_ID
              value: '1'
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: '1@:29093'
            - name: KAFKA_LISTENERS
              value: >-
                PLAINTEXT://:29092,CONTROLLER://:29093,PLAINTEXT_HOST://0.0.0.0:9092
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_LOG_DIRS
              value: /tmp/kraft-combined-logs
            - name: CLUSTER_ID
              value: MkU3OEVBNTcwNTJENDM2Qk
            - name: KAFKA_NUM_PARTITIONS
              value: '15'
          {{- if .Values.isOpenShift }}
          securityContext:
            runAsUser: 0
          {{- end }}
          ports:
            - containerPort: 9092
              protocol: TCP
          imagePullPolicy: IfNotPresent
          image: "{{ .Values.repository }}cp-kafka:7.4.1"
      securityContext: {}
