{{- if .Values.isOpenShift }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: api
  labels:
    getapp: api
    chart: {{ template "getapp-api.chart" . }}
    draft: {{ .Values.draft | default "draft-app" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    gitlabrelease: "{{ .Values.gitlabrelease }}"
spec:
  host: api-{{ .Values.nameSpace }}.{{ .Values.routeMainlUrl }}
  to:
    kind: Service
    name: getapp
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
{{- end }}
