apiVersion: v1
kind: Service
metadata:
  name: getapp
  labels:
    getapp: api
    chart: {{ template "getapp-api.chart" . }}
    draft: {{ .Values.draft | default "draft-app" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    gitlabrelease: "{{ .Values.gitlabrelease }}"
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    getapp: api

