kind: Service
apiVersion: v1
metadata:
  name: kafka-broker-service
spec:
  ports:
    - name: http1
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: http2
      protocol: TCP
      port: 29092
      targetPort: 29092
    - name: http3
      protocol: TCP
      port: 29093
      targetPort: 29093
  type: ClusterIP
  selector:
    app: kafka-broker

